// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEfJPYtI2MDaMEzUfUk4cJ3dd_DuHqnnM',
    appId: '1:242796974269:web:a69b3aedad8b663491a7d4',
    messagingSenderId: '242796974269',
    projectId: 'okno-970d4',
    authDomain: 'okno-970d4.firebaseapp.com',
    storageBucket: 'okno-970d4.appspot.com',
    measurementId: 'G-LH80B5ZK9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL10cBvs1bWWv3sQHHfsHCTxD-WvQZgMM',
    appId: '1:242796974269:android:c9af86d06cc0e80891a7d4',
    messagingSenderId: '242796974269',
    projectId: 'okno-970d4',
    storageBucket: 'okno-970d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdOvCsNt5ocJSUSmuKr1bzpBlrxJfO9As',
    appId: '1:242796974269:ios:845ac53e5aa7d09291a7d4',
    messagingSenderId: '242796974269',
    projectId: 'okno-970d4',
    storageBucket: 'okno-970d4.appspot.com',
    iosClientId: '242796974269-gis5cce9qgaehb5ku7c80t8gaesp1a40.apps.googleusercontent.com',
    iosBundleId: 'com.example.okno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdOvCsNt5ocJSUSmuKr1bzpBlrxJfO9As',
    appId: '1:242796974269:ios:52da3ac5e532281891a7d4',
    messagingSenderId: '242796974269',
    projectId: 'okno-970d4',
    storageBucket: 'okno-970d4.appspot.com',
    iosClientId: '242796974269-ncjun2pbgpp215m3n7j7dhhqh0po67uk.apps.googleusercontent.com',
    iosBundleId: 'com.example.okno.RunnerTests',
  );
}
